### ISSUE TITLE
wrong file meta is exported in multilanguage environments

### ISSUE THREAD

**Issue by scsskid** [d4l-data4life/kirby3-static-site-generator#16]
wrong file meta is exported in multilanguage environments

## Expected Behavior

get meta from correct language specific file

## Current Behavior

when accessing meta data of a image file, only main language data gets exported (e.g. caption text of image.jpg.de.txt) this only occurse when ecporting to static site, not when accessing the site via kirby

when accessing the other language, the meta content of main language gets displayed

## Steps to Reproduce

get meta field of file in language other than main language

```
#  image.jpg.en.txt
caption: This is english caption
```

`$file->caption()->kt()`

## Context

kirby 3.1
kirby3-static-site-generator 1.0.3

**Comment by jonathan-reisdorf** [comment]
will be fixed by https://github.com/d4l-data4life/kirby3-static-site-generator/pull/18
