### ISSUE TITLE
Duplicate meta tags generated in each html file

### ISSUE THREAD

**Issue by HashandSalt** [d4l-data4life/kirby3-static-site-generator#21]
Html output contains duplicate meta tags if you have that plugin installed also.

## Expected Behaviour

Generated page should be as it is in the browser

## Current Behaviour

If you have the Meta Tags plugin installed as well, you get duplicate meta tags rendered in each html file.

## Steps to Reproduce

- Add the meta tags plugin to a site as well as the static site generator.
- Setup meta tags for each page
- Use the blueprint button method to generate the static files
- Check the html output and you will see multiple meta tags in each html file, which i think are duplicated the same number of times as there are pages. (ie if the site has 5 pages, you will end up with 5 meta description tags in each page).

## Context

Kirby 3.2.5

**Comment by jonathan-reisdorf** [comment]
This is the conflicting plugin: https://github.com/pedroborges/kirby-meta-tags
The bug is not in the static site generator plugin but in the meta tags plugin.
Anyway, I've fixed the issue, a PR has been created here: https://github.com/pedroborges/kirby-meta-tags/pull/19
