### ISSUE TITLE
Run the generator from command line

### ISSUE THREAD

**Issue by arnabwahid** [d4l-data4life/kirby3-static-site-generator#26]
Is there a way I can run the generator from command line?

**Comment by jonathan-reisdorf** [comment]
Hi @arnabwahid,
there's no cli tool, but you can create e.g. a `generate.php` file in the root of your project with a content like this:

```
<?php
  require('./index.php');
  $kirby = kirby();
  $staticSiteGenerator = new D4L\StaticSiteGenerator($kirby);
  $list = $staticSiteGenerator->generate();
  echo json_encode($list, JSON_PRETTY_PRINT);
```

and then you can run `php generate.php` from the command line.
Does that work for you?

**Comment by jonathan-reisdorf** [comment]
Closing this because a solution has been provided
