### ISSUE TITLE
preserve[] in config, not doing what is expected

### ISSUE THREAD

**Issue by shoesforindustry** [d4l-data4life/kirby3-static-site-generator#27]
I presumed that setting an array of files in the ` 'preserve' => []` section of the config.php would mean that those files would be copied to the static folder?

e.g.
`'d4l' => [
      'static_site_generator' => [
          ...
          'preserve' => ['favicon.ico']
          ....
      ]
  ],
  
Is this not correct? Because it does not seem to work?
Any ideas?

Kirby 3.3.5
PHP 7.4.5

**Comment by jonathan-reisdorf** [comment]
Hi @shoesforindustry ,
the `preserve` property is meant to be used when you have a (e.g. manually copied) file or folder in the target directory which should not be deleted every time you generate the static site.
So, you'd once have to copy `favicon.ico` over to your generated folder and it would stay there.
If you want to copy it over every time by the plugin, you'll currently have to use implementation option 1 (https://github.com/d4l-data4life/kirby3-static-site-generator#1-directly-eg-from-a-kirby-hook), where you can add a second argument when instantiating the `D4L\StaticSiteGenerator` class (`$pathsToCopy`).

**Comment by shoesforindustry** [comment]
Apologies Jonatnan, I had misunerstood the purpose, now I get what you mean. I appreciate the speedy reply and the software.
