### ISSUE TITLE
Not working with imgix plugin

### ISSUE THREAD

**Issue by pfrlv** [d4l-data4life/kirby3-static-site-generator#34]
Images on the my site are processed by the plugin https://github.com/diesdasdigital/kirby-3-imgix and of course due to changes in `media.class.php` the plugin does not work.

**Comment by jonathan-reisdorf** [comment]
@pfrlv thanks for reporting. Unfortunately it took me a while to look at the issue.
Can you please try out if applying the changes of the following PR works? https://github.com/d4l-data4life/kirby3-static-site-generator/pull/38
Additionally to the code from PR you need to add the following to your config inside the `d4l.static_site_generator` section:
```
      'media_plugin' => 'diesdasdigital/imgix',
      'media_url_transform' => function($url, $kirby) {
        return explode('?', str_replace($kirby->option('imgix.domain', '/'), '/', $url))[0];
      }
```
