### ISSUE TITLE
404 page handling

### ISSUE THREAD

**Issue by mciszczon** [d4l-data4life/kirby3-static-site-generator#35]
Hi!

Thanks for this cool plugin, I love how smooth it works. While testing it I found out that it does not handle the error page correctly, or at least the way I'd want it to.

Here's a short description of my feature request:

## Expected Behavior

I generate a static site from a Kirby site which has an error page (at `/error` URL), and this page is automatically shown for any non-existent URLs (404).

This generated static site also automatically handles non-existent URLs and shows the error page for them.

## Current Behavior

Non-existent URLs do not automatically show the error page, instead a generic 404 Not Found error page is provided (depending on the server software).

Error page is only available on the original URL that it was set to (usualy `/error`).

## Possible Solution

I think it would be relatively easy to achieve by changing your script to also place a `.htaccess` file in the static folder.

There a one line only is required:

```
ErrorDocument 404 /url-to-error-page
```

This will automatically show the content of the error page for any URLs that return 404 from the server. Thus, the original behavior of the error page is transferred in 100% to the static site.

This is safe, as placing `.htaccess` file in a subfolder only changes the Apache settings for the given folder and it's children. No risk here that it will override the default Kirby settings.

## Context

Here are the version of both Kirby and the plugin. Both installed using composer.

`getkirby/cms`: v3.4.4
`d4l/kirby-static-site-generator`: v1.0.10

**Comment by mciszczon** [comment]
Now that I think about it, playing with the web server configuration should not be a task of this plugin. A custom `.htaccess` would only work for Apache anyway, and it should be provided in another fashion (for example as a part of CI/CD process).

I'll close this issue.

**Comment by bytesource** [comment]
Your plugin makes turning a Kirby site into a static site a breeze. Love it!

Currently, I just have one problem, which is the same as mentioned by @mciszczon:

When uploading the static folder to Cloudflare Pages, in case of a "page not found" error, Cloudflare Pages will look for the closest `404.html` file, going up to the root folder:
https://developers.cloudflare.com/pages/platform/serving-pages/#not-found-behavior

However, when running the Kirby static site generator, the error page is located at `<static folder>/error/index.html`.

Thinking that setting up a custom route might to the trick, I added the following configuration for `custom_routes`:
```
'd4l' => [
        'static_site_generator' => [
            'custom_routes' => [
               [ './error/index.html' => './404.html' ],
            ],

            'endpoint' => 'update-static-site',
        ]
    ]
```
Unfortunately, generating the static site did not add `404.html` to the root folder. 

Could you help me correct the custom route configuration? That would be great!

Cheers, 

Stefan

**Comment by bytesource** [comment]
Hi, 

I only just realized that my code example from the comment above is wrong. 

So, I changed it to this, before running the static site generator again:

``` php
'd4l' => [
        'static_site_generator' => [
            'custom_routes' => [
               [ 
                   'path' => '404.html', 
                   'page' => 'error' 
               ],
            ],

            'endpoint' => 'update-static-site',
        ]
    ]
```

Unfortunately, the output is always in the form of `path/index.html`:

![image](https://user-images.githubusercontent.com/610307/158554176-68520490-a5ca-4a1d-84c7-1ea7d011cc3f.png)

What I need is a way to move and _rename_ a file, e.g., going from `/error/index.html` to `/404.html`.

I don't think custom routes solve this issue, but can you think of another way to automatically place `404.html` into the root folder?

Any suggestions are highly welcome!

Cheers, 

Stefan
