### ISSUE TITLE
when using with kirby-webpack, bundled css & js file path is off

### ISSUE THREAD

**Issue by perpetualgrimace** [d4l-data4life/kirby3-static-site-generator#39]
Hi, I just installed [kirby-webpack](https://github.com/brocessing/kirby-webpack) as well as kirby3-static-site-generator and I'm trying to get them to play nicely together.

kirby-webpack has a folder structure where most of the standard kirby stuff is in a subfolder named `www/`. It also has a build script which creates js and css bundles in `www/assets/builds/`.

When I run the static site generator, everything looks good so far, except in `www/static/index.html`, it seems to be looking for the assets in the wrong directory (`/www.assets/builds/` instead of `www.assets/builds`). I tried adjusting the `base_url` option, but that only seemed to create the `static/` folder inside a new `www/` folder. 😅

I have the latest version of Kirby and both plugins.

Also, for context, I'm trying to create a static version of a site I'm currently working on in order to host it via Netlify so my client can see my work.

I feel like I'm missing something simple here. Any ideas?

**Comment by jonathan-reisdorf** [comment]
Hi @perpetualgrimace :wave: thanks for reporting! I've tried cloning kirby-webpack and adding the plugin and it seems like everything is working, so unfortunately I can't reproduce the issue (yet). I assume you are using [implementation option 3](https://github.com/d4l-data4life/kirby3-static-site-generator#3-by-using-a-static-site-generator-field), right? If so, could you please post your d4l.static_site_generator section from the config here? Thank you!
(I stumbled on one issue, which is that config.localhost.php sets `HTTP_X_FORWARDED_PROTO` on localhost, which will add live reload for the css, which doesn't work anymore without the webpack dev server in the static website context - but what you reported seems to be a different issue)

**Comment by jonathan-reisdorf** [comment]
By the way: The issue I just mentioned can be solved by adding these lines on top of  the `isWebpack()` function in the kirby-webpack plugin:
```php
$kirby = kirby();
if ($kirby->request()->url()->path()->toString() === 'api/' . $kirby->option('d4l.static_site_generator.endpoint')) {
  return false;
}
```

**Comment by perpetualgrimace** [comment]
Thanks for the response! I actually launched the site the day you replied so I didn't get a chance to try out this fix 😂

Next project, I'll try this out and report back.
