### ISSUE TITLE
 No route found for path: "undefined" and request method: "POST"

### ISSUE THREAD

**Issue by timotheegoguely** [d4l-data4life/kirby3-static-site-generator#5]
## Expected Behavior

Generate a static version of my website

## Current Behavior

I get the following error message when clicking the `Generate a static version of the site` button inside the panel:

> No route found for path: "undefined" and request method: "POST"

## Possible Solution

I don’t understand if I need to replace `null` for the `endpoint` option, I’m not very used to webhooks…

## Context

Kirby 3.2.0
kirby3-static-site-generator 1.0.2 installed manually (all the files in a `plugins/static-site-generator` folder
macOS 10.14.5

I’m trying yo use the 2-3 method.
Here is my `config.php` file:

```php
<?php

return [
  'debug' => true,
  'languages' => true,
  'd4l' => [
     'static_site_generator' => [
       'endpoint' => null, # set to a string to use the built-in webhook, e.g. when using the blueprint field
       'output_folder' => './static', # you can specify an absolute or relative path
       'base_url' => '/', # if the static site is not mounted to the root folder of your domain, change accordingly here
     ]
   ]
];
```

What am I doing wrong? 🤔

**Comment by jonathan-reisdorf** [comment]
Hi @timotheegoguely, you can choose your own uri there, e.g.
```
'endpoint' => 'generate-static-site',
```
or
```
'endpoint' => 'deployment/generate',
```
etc. would all work. This is just to give you the flexibility to choose a url under which the static site generator can be called. It does not really matter what you choose here, it will all work as long as it is not `null`.

**Comment by timotheegoguely** [comment]
Thank you @jonathan-reisdorf for your quick answer, I get the idea.
I now have a `Call to a member function crop() on null` error message, but I’m not sure it’s related to your plugin…

**Comment by jonathan-reisdorf** [comment]
@timotheegoguely it might be related. Do you have `->crop(` somewhere in your templates or snippets and if so, can you paste the code here? Thanks :)

**Comment by jonathan-reisdorf** [comment]
@timotheegoguely I am able to reproduce the issue

![image](https://user-images.githubusercontent.com/8958624/60818019-140f5f80-a19d-11e9-90a2-423d743ab614.png)

when I have a page (can be any page, the plugin is rendering all pages) where I reference an image which does not exist anymore.
Example:
```
<?php echo $page->file('test.jpg')->crop(800, 1000) ?>
```
In this example let's assume `test.jpg` existed before, that's why it's referenced here. Later the file is deleted, but the content or code is not updated and still points to the file name.

**Comment by timotheegoguely** [comment]
Thanks for your help, I fixed my code and now everything is generating correctly 🎉 
I have other questions now but I’m opening a new issue for that.

**Comment by jonathan-reisdorf** [comment]
@timotheegoguely I have created two new issues from this one in order to enhance usability of the plugin
