### ISSUE TITLE
Escaped html tag appears in custom help text field

### ISSUE THREAD

**Issue by ShallowRed** [d4l-data4life/kirby3-static-site-generator#51]
## Expected Behavior

Being able to set custom help text in plugin blueprint

## Current Behavior

A \<p\> tag gets escaped and wraps my custom help text when I provide one
Other fields are not impacted.

Without custom help:

<img width="315" alt="Capture d’écran 2022-05-06 à 08 46 57" src="https://user-images.githubusercontent.com/48523123/167081782-e5db2dfc-47be-40ca-b679-034483a1295a.png">

<img width="511" alt="Capture d’écran 2022-05-06 à 08 46 19" src="https://user-images.githubusercontent.com/48523123/167081773-801a2625-c867-4c4a-8356-c7f395204d2c.png">

With custom help:

<img width="318" alt="Capture d’écran 2022-05-06 à 08 47 16" src="https://user-images.githubusercontent.com/48523123/167081783-b138881d-9b9b-4eeb-bbab-5c5f4046d238.png">

<img width="487" alt="Capture d’écran 2022-05-06 à 08 47 24" src="https://user-images.githubusercontent.com/48523123/167081785-0a1a6e1a-743b-4e5e-a412-cd94455aa174.png">

## Context

Installation of kirby and plugin via composer
Bug happening on macOs, windows and remote server
Plugin used with blueprint field
kirby 3.6.5
d4l static site generator: 1.3.0

**Comment by jonathan-reisdorf** [comment]
Thank you, this must have been introduced with one of the newer Kirby versions
