### ISSUE TITLE
Generated content does not respect page language

### ISSUE THREAD

**Issue by Sunnyka98** [d4l-data4life/kirby3-static-site-generator#57]
## Expected Behavior

The expected behavior is that the english pages, show the english content, and the german pages show the geman content. 

## Current Behavior

On a local hosted kirby all pages show correct, but when using the static site generator, the generated pages only show in the default language. (In my example always german) The translation through the t() function seems to be correct but not the other content, which came from the txt files. 

## Steps to Reproduce

I made a litte public repository: https://github.com/Sunnyka98/SSG-Problem/ 
There is the home page in two languages, a footer and header snippet and it is based on the plain kirby kit. 
Just start the static site generator manually with the supplied php script. `php generate.php`

## Context

Kirby: 3.6.6
SSG: 1.5.0
Windows and Linux were tested.

The plugin is a submodule in my repository. I think there are no special configurations.

**Comment by jonathan-reisdorf** [comment]
Thank you @Sunnyka98! We've observed the same also in another repository. I will fix and let you know when there is a new version of the static site generator available to test. Thanks :)

**Comment by jonathan-reisdorf** [comment]
I've published version 1.5.1 now which should solve your issue. If something does not work as expected please let me know, thanks for bringing this up!

**Comment by Sunnyka98** [comment]
Thank you for this quick fix!
