### ISSUE TITLE
Unable to generate sitemap

### ISSUE THREAD

**Issue by robbertrosario** [d4l-data4life/kirby3-static-site-generator#59]
## Expected Behavior

I am using this sitemap snippet: https://getkirby.com/docs/cookbook/content/sitemap by Bastian. But it doesn't generate an actual sitemap.xml file it just starts rendering the xml when you access the route.

I've tried using the `ready` function as per README, but the `custom_routes` expect a page id, but the above sitemap snippet is not an actual page? and therefore has no page id?

## Current Behavior

Sitemap is not generated

## Context

Kirby version: 3.7
Plugin version: 1.5.1

Installed using composer

**Comment by ShallowRed** [comment]
To generate a static sitemap I use `new Page()` in the plugin's config ready option :

```php
// config.php
return [
	'ready' => function() {
		return [
			'd4l.static_site_generator' => [
				'custom_routes' => return [[
					'path' => '/sitemap.xml',
					'page' => new Page([
						'template' => 'sitemap',
						'slug' => 'sitemap',
					]),
				]];
			],
		];
  	}
];
```

I have a `sitemap.php` in the template folder, I don't what you should do with your snippet from the cookbook. Creating a `sitemap.php` template which just calls your snippet should work.

**Comment by robbertrosario** [comment]
That seems to work thanks!

**Comment by ShallowRed** [comment]
From the documentation :

```php
$customRoutes = [
  [ // advanced configuration
    'path' => 'foo/baz',
    'page' => page('some-page-id'),
    'data' => [
      'foo' => 'bar'
    ]
  ]
];
```

For your previous question, notice how `page('some-page-id')` returns a page object (as when using `new Page()`), it also says that you can use both a page id or a page object.

For pagination, it says that you can pass data in the `'data'`option and check [here](https://getkirby.com/docs/guide/templates/controllers#arguments-from-page-render-in-route) to see how you can use it from a controller. I believe the plugin will use `$page->render($data);`, so `$foo` will be accessible as an argument of your controller's returned function.

From there you should be able to generate pagination, there would be lots of ways to do it.

For example, say you want to paginate some 'posts' in a page called 'posts-archive', and you want to have n posts per page.

```php
// in config.ready

$chunks = array_chunk($posts, $n_posts_per_page); 

$n_chunks = count($chunks);

$custom_routes = A::map($chunks, function ($chunk) use ($n_chunks) {

	static $index = 0;
	++$index;

	return [
		'path' => 'posts-archive/' . string ($index),
		'page' => page('posts-archive'),
		'data' => [
			'posts' => $chunk,
			'pagination' => [
				'count' => $n_chunks,
				'current' => $index,
				'prev' => $index - 1,
				'next' => $index + 1,
			],
		],
	];
});
```
Then in `controllers/posts-archive.php`, retrieve $posts and $pagination as arguments of your returned function to render your posts thumbnails and your navigation bar (I guess);
