### ISSUE TITLE
Include feeds from the kirby3-feed plugin

### ISSUE THREAD

**Issue by paresy** [d4l-data4life/kirby3-static-site-generator#62]
I'd love to include the XML feed into my static build that i already can access using my custom route `http://127.0.0.1:8000/de/feed`

The part of the config.php that might be relevant:

```
    'routes' => [
        [
            'pattern' => 'de/feed',
            'method' => 'GET',
            'language' => 'de',
            'action'  => function () {
                $options = [
                    'title' => 'My Site',
                    'sort' => false,
                ];
                return site()->index()->feed($options);
            }
        ],
    ....
```

## Steps to Reproduce

I hoped to use the custom routes feature to include the feed:

```
$staticSiteGenerator->setCustomRoutes([
    [
        'path' => '/feed.xml',
        'page' => 'de/feed'
    ],
]);
```

But somehow it does not work. Am i on the right path or doesn't it work like this?

## Context

Kirby 3.7.5, Kirby3-Feed: 1.5.2, SSG 1.5.1

**Comment by matthiasjg** [comment]
@paresy I'm using _kirby3-feed_ w/ my plugin to generate a static site + feeds. Maybe either the code or even the plugin is helpful for you?

https://github.com/matthiasjg/kirby3-static-site-composer/blob/main/index.php#L89

Disclaimer: plugin not released yet, only `dev`

https://packagist.org/packages/matthiasjg/kirby3-static-site-composer

hth

**Comment by jonathan-reisdorf** [comment]
Hi @paresy, sorry for the late reply. So far, the custom routes feature only supports rendering pages, not other routes, so `page` should refer to either a page object or a page ID. I'll try to see if it's possible to extend the plugin to let static site custom routes point to dynamic kirby routes and render them. (The route then must not call `exit` or `die`, and it must not directly echo but return a response or a string)

**Comment by paresy** [comment]
@jonathan-reisdorf That would be awesome! If you have anything to test, i will be glad to do so and give you feedback. Thanks again 👍

**Comment by jonathan-reisdorf** [comment]
Thank you, I have created this PR: https://github.com/d4l-data4life/kirby3-static-site-generator/pull/63 which solves the issue by implementing rendering of dynamic routes (incl. patterns and action arguments).

All you'd have to do with these changes is:
```
$staticSiteGenerator->setCustomRoutes([
    [
        'path' => 'feed.xml',
        'route' => 'de/feed'
    ],
]);
```
Happy to hear if that works to solve the problem. Thanks :)

**Comment by paresy** [comment]
Unfortunately it does not work yet. I could trace it down to this line returning `NULL`. `$routePath` is properly set to `de/feed`.
>     $routeResult = kirby()->router()->call($routePath, 'GET');

My route is configured like showed in in the 1. post. Can you maybe post the route configuration which you have tested?

**Comment by paresy** [comment]
The problem was the specific language, that was set on the route `'language' => 'de'`. As i don't really need it, i have removed this part from the config.php and it works now. Maybe you should add a hint, that this does not work on multi language sites with a route being bound to a specific language.

**Comment by jonathan-reisdorf** [comment]
Ah :bulb: I did indeed not test for that. Perhaps I can make that work, too, else as you suggested I'll add a note to the readme. Thanks!
