### ISSUE TITLE
Version 1.8 ?

### ISSUE THREAD

**Issue by Anjade** [d4l-data4life/kirby3-static-site-generator#71]
I have deleted the dir and uploaded the last version 1.8.
Kirby says that 1.7 is installed.

**Comment by Anjade** [comment]
C:\Users\Name\Downloads\kirby3-static-site-generator-master(2)\static-site-generator\composer.json(3): "version": "**1.7.0**",

**Comment by jonathan-reisdorf** [comment]
version has been updated
