### ISSUE TITLE
/api/generate-static-site/

### ISSUE THREAD

**Issue by Anjade** [d4l-data4life/kirby3-static-site-generator#73]
I use some code for pagination in blog-pages like this:

`    <?php if ($pagination->hasPages()): ?>
        <?php if ($pagination->hasPrevPage()): ?>
            <a href="<?= $pagination->prevPageUrl() ?>"><<</a>
        <?php endif ?>
        
        <?php foreach ($pagination->range(5) as $r): ?>
            <a <?= $pagination->page() === $r ? ' style="font-weight:bold"' : ' ' ?> href="<?= $pagination->pageURL($r) ?>"><?= $r ?></a>
        <?php endforeach ?>
     
        <?php if ($pagination->hasNextPage()): ?>
          <a href="<?= $pagination->nextPageUrl() ?>">>></a>
        <?php endif ?>
    <?php endif ?>`

It produces links like /.../notes/page:{integer}; while these links are replaced everywhere else in the right way, i get something like /api/generate-static-site/page:{integer} for the pagination links. Is there any information where in the plugin this is produced? Or when or why it is produced?

I tried to preg_replace these links in the plugin itself, but there is no info about the $language, so i cant replace /api/generate-static-site/page:{integer} to something like /en/notes/page:2 or /en/notes/2, what i finally need here.

The only way to make the pagination working now is to replace the links like $pagination->nextPageUrl() with something real like /de/notes/page:{integer}. How can we make the addon working with the kirby produced links also?

I have send urls to kirby and kirby-static and ftp to watch it on a running site.

**Comment by jonathan-reisdorf** [comment]
fixed in PR, see also https://github.com/d4l-data4life/kirby3-static-site-generator/issues/72
