### ISSUE TITLE
Regex page:{x}

### ISSUE THREAD

**Issue by Anjade** [d4l-data4life/kirby3-static-site-generator#76]
$pagination->prevPageUrl()
$pagination->nextPageUrl()

are still not regexed?

There should be an easy way to regex page:2 till page:{x} 
with /{x}

Like: options_regex_links [

page:{INT} => {INT}

**Comment by jonathan-reisdorf** [comment]
Sorry but I do not understand the issue. We can also not provide technical Kirby or PHP support unfortunately. Closing the issue
