### ISSUE TITLE
Problems with virtual translated pages 

### ISSUE THREAD

**Issue by Sunnyka98** [d4l-data4life/kirby3-static-site-generator#81]
## Expected Behavior

I use the static site generater and [this plugin](https://github.com/bnomei/kirby3-feed) to generate a xml feed. 

I expect that the static site generater also translate virtual xml pages. 

## Current Behavior

At the version 1.12.0 of the static site generater the xml page is not translatet, so the default language is used.

## Possible Solution

Possible the error is on [line 215](https://github.com/d4l-data4life/kirby3-static-site-generator/blob/master/class.php#L215), there the _setPageLanguage - funktion checked if the page is exist. Without the condition in [line 227](https://github.com/d4l-data4life/kirby3-static-site-generator/blob/master/class.php#L227) everything worked. 

## Steps to Reproduce

I get a plain kit from kirby. Add some pages, the feed plugin from bnomei and the static site generator.
I made a [little repo](https://github.com/Sunnyka98/SSG-Feed) to show the error. 
If you run the generator.php, an look than in the build folder to the feed-en.xml the title and the description of the single pages are on the default language german.

## Context

I use the  kirby version 3.9.6, version 1.12 from the static-site-generater on Windows and the plugin is manually installed as submodule. I trigger the static site generator manually via script.

**Comment by jonathan-reisdorf** [comment]
@Sunnyka98 thanks a lot for reporting this bug and providing the repo for reproducing it 🙌 
Release [1.12.1](https://github.com/d4l-data4life/kirby3-static-site-generator/releases/tag/1.12.1) should solve your issue. Let me know if something else is broken, thanks!
