### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [d4l-data4life/kirby3-static-site-generator#86]
> Undefined constant "D4L\DS"
> "/site/plugins/kirby3-static-site-generator-1.12.2/class.php:405"

**Comment by jonathan-reisdorf** [comment]
Hi @afbora, thank you for letting us know 👍  If this is the only breaking change, it will be easy to fix, I'll hopefully find time to test it this week. It's also not decided yet if we'll continue (long-term) maintenance of this plugin for K4, and if so, if it will be done in this repo or if there will be a `kirby4` repo.
