### ISSUE TITLE
Kirby4

### ISSUE THREAD

**Issue by anjacom** [d4l-data4life/kirby3-static-site-generator#89]
Is there a version for kirby4, please?

**Comment by dimejo** [comment]
[Release 1.13.0](https://github.com/d4l-data4life/kirby3-static-site-generator/releases/tag/1.13.0) should already be compatible with Kirby 4.

**Comment by jonathan-reisdorf** [comment]
Thank you, yes, the latest release should be compatible with Kirby 4 despite the repository name. (Perhaps it makes sense to rename the repo to `kirby-static-site-generator`.)
Closing the issue. Let me know if you run into an issue when using the site generator with Kirby 4.
